##
# Set up and configure postgres
##
- name: Install and configure db
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: latest
  become: yes

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: yes

- name: Create database
  postgresql_db: name={{ app_name }}
  become_user: postgres
  become: yes

- name: Configure a new postgresql user
  postgresql_user:
    db={{ app_name }}
    name={{ db_user }}
    password={{ db_password }}
    priv=ALL
    role_attr_flags=NOSUPERUSER
    encrypted=yes

  become: yes
  become_user: postgres
  notify:
    - restart postgres
